### PR TITLE
permissions v2

### PR DESCRIPTION
**Pull request by JellyWX**
targeting develop as this relies on git serenity. basic support for permissions v2 as a new `default_member_permissions` field on the command macro.

### CODE REVIEW

**Comment by kangalio** [comment]
Thank you!

Why didn't you adapt the existing required_permissions for this?

**Comment by JellyWX** [comment]
I wasn't certain about the idea of having what would essentially be two separate permission check systems under the same name, as prefix commands would still check internally with the bot and slash commands would no longer.

If you're okay with that I'll change it. I don't use prefix commands at all so it doesn't really affect me

**Comment by kangalio** [comment]
Okay cool, yeah I would prefer reusing required_permissions for simplicity, and to avoid existing users having to port to the new field

The fact that Discord permissions v2 work slightly differently, (guild owners can modify permission checks if they want (?)) is fine I think

**Comment by JellyWX** [comment]
The issue here is with subcommands, since those don't use permissions properly I don't think (on permissions v2). Also, I haven't been able to test this commit properly yet due to https://github.com/discord/discord-api-docs/issues/4856

**Comment by kangalio** [comment]
By now I feel like it's better to have a separate attribute argument `default_member_permissions` after all. That way, users explicitly choose to opt in to the subtle changes: guild owners being able to change permissions; no subcommand specific permissions

**Comment by kangalio** [comment]
@jellywx Are you ok with the PR being merged like this?

**Comment by JellyWX** [comment]
Yep,looks fine by me. Thanks!

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request merged**
