### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by cheesycod**
Untested

### CODE REVIEW

**Comment by cheesycod** [comment]
@kangalio fixed builds on serenity-next

**Comment by kangalio** [comment]
Please also commit the updated Cargo.lock to fix CI

**Comment by cheesycod** [comment]
uploaded

**Comment by cheesycod** [comment]
why is it still failing

**Comment by kangalio** [comment]
See the CI logs:

> error[E0433]: failed to resolve: could not find `bridge` in `client`
   --> src/prefix_argument/macros.rs:261:40
    |
261 |             shard: ::serenity::client::bridge::gateway::ShardMessenger::new(
    |                                        ^^^^^^ could not find `bridge` in `client`

https://github.com/serenity-rs/serenity/pull/2380

**Comment by kangalio** [comment]
I was going to fix this issue myself but I cannot edit this PR unfortunately

**Comment by cheesycod** [comment]
ugh, how do i give maintainers the ability to edit prs?

**Comment by cheesycod** [comment]
Making a new PR

**Pull request closed without merging**
