### PR TITLE
add poise::Context::category_id

### PR DESCRIPTION
**Pull request by Monadic-Cat**
It'd be nice if we could easily fetch the containing category for the channel a command is invoked in.
This method tolerates the Serenity cache not being populated (and thus has to be `async` in order to fetch that info from Discord).

### CODE REVIEW

**Comment by kangalio** [comment]
I changed the implementation to use channel_id.to_channel(), which already implements the cache fallback on HTTP error mechanism (plus it also supports the new temp_cache feature). This also means the function now compiles without cache feature enabled (and it has slightly fewer lines of code). I also added some more documentation.

But looking at this, this function is basically just a wrapper around `to_channel().guild().parent_id`, and there's loads other fields on GuildChannel that should have such functions, if there's one for parent_id. So if anything there should probably just be a function for `to_channel().guild()` and the user can access the field themselves. However there's also other channel types that could warrant such a method. Following that train of reasoning, I'm not sure if any new method should be added at all, to be honest...?

**Comment by Monadic-Cat** [comment]
Dunno. I wasn't aware that `to_channel()` existed, and I had to go back and read Discord docs to discover "oh it's probably not exposed here because an Interaction object doesn't carry that field", and then go figure out where to grab the category ID from instead.
I expected this method to be here initially because both `channel_id()` and `guild_id()` are here, but if that's not compelling, I'm not super attached to this being merged, since it's just a wrapper for existing public API.

**Comment by kangalio** [comment]
> I wasn't aware that to_channel() existed, and I had to go back and read Discord docs to discover "oh it's probably not exposed here because an Interaction object doesn't carry that field", and then go figure out where to grab the category ID from instead.

Sounds like I should improve documentation. I tried https://docs.rs/poise/latest/poise/#finding-serenity-methods to point people to the very useful methods on the Id types but that section is evidently not visible or understandable enough. What do you think would help the docs so that you wouldn't have had such a hard time discovering how to get category_id?

**Comment by kangalio** [comment]
Added more docs in 5ba00794e65766a9c4d72a1560043940210b9f89

https://kangalioo.github.io/poise/develop/poise/index.html#useful-serenity-methods

**Pull request closed without merging**
