### PR TITLE
Refinements to builtins::help

### PR DESCRIPTION
**Pull request by docwilco**
- Deduplicated some code
- Deal better with subcommands and context menu combos
- Show parameters for commands in single command help
- Show all invocations (slash/prefix/context menu) in single command help

### CODE REVIEW

**Comment by docwilco** [comment]
Since this is on `next` is it time to crank up MSRV? Or do you want me to get rid of let-else?

**Comment by kangalio** [comment]
I'd rather you get rid of let-else for now

**Comment by docwilco** [comment]
You need anything else from me for this?

**Comment by kangalio** [comment]
Nah, just procrastinated to review

Thank you for contributing this!

**Pull request merged**
